-------------------- Log Start | Fri Dec  8 07:20:50 2023 --------------------
data_path: /home/klipper/printer_data
is_default_data_path: False
config_file: /home/klipper/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: False
instance_uuid: 38bde6e726f04261980b00492c0da115
unix_socket_path: /home/klipper/printer_data/comms/moonraker.sock
software_version: v0.8.0-142-gee62d07
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/klipper/printer_data/logs/moonraker.log
python_version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
klippy_uds_address = /home/klipper/printer_data/comms/klippy.sock

[authorization]
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128
cors_domains = 
	*.lan
	*.local
	*://localhost
	*://localhost:*
	*://my.mainsail.xyz
	*://app.fluidd.xyz

[octoprint_compat]

[history]

[update_manager]
channel = dev
refresh_interval = 168

[update_manager mainsail-config]
type = git_repo
primary_branch = master
path = ~/mainsail-config
origin = https://github.com/mainsail-crew/mainsail-config.git
managed_services = klipper

[update_manager mainsail]
type = web
channel = stable
repo = mainsail-crew/mainsail
path = ~/mainsail

#################################################################
All Configuration Files:
/home/klipper/printer_data/config/moonraker.conf
#################################################################
Unsafe Shutdown Count: 19

System Info:

***python***
  version: sys.version_info(major=3, minor=10, micro=12, releaselevel='final', serial=0)
  version_string: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

***cpu_info***
  cpu_count: 4
  bits: 32bit
  processor: armv7l
  cpu_desc: ARMv7 Processor rev 5 (v7l)
  serial_number: 2c00081e46729b2
  hardware_desc: Allwinner sun8i Family
  model: 
  total_memory: 503492
  memory_units: kB

***sd_info***
  manufacturer_id: 1b
  manufacturer: Samsung
  oem_id: 534d
  product_name: EB1QT
  product_revision: 3.0
  serial_number: 9d8557b0
  manufacturer_date: 7/2019
  capacity: 29.8 GiB
  total_bytes: 32010928128

***distribution***
  name: Armbian 23.8.3 jammy
  id: ubuntu
  version: 22.04
  version_parts: {'major': '22', 'minor': '04', 'build_number': ''}
  like: debian
  codename: jammy
  release_info: {}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator

Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['network-online.target', 'sysinit.target', '-.mount', 'system.slice']
**After=['systemd-journald.socket', 'network-online.target', 'sysinit.target', '-.mount', 'system.slice', 'basic.target']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/klipper/printer_data/systemd/moonraker.env
**ExecStart=/home/klipper/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=/home/klipper/moonraker
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=klipper

Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['-.mount', 'sysinit.target', 'system.slice']
**After=['systemd-journald.socket', 'network-online.target', 'sysinit.target', '-.mount', 'system.slice', 'basic.target']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/klipper/printer_data/systemd/klipper.env
**ExecStart=/home/klipper/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/klipper/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=klipper
Git Repo moonraker: No warnings detected
Git Repo klipper: No warnings detected
Git Repo mainsail-config: No warnings detected
Klipper Version: v0.11.0-277-g21b78429
2023-12-08 10:20:50,303 [machine.py:_parse_network_interfaces()] - Error processing network update
Traceback (most recent call last):
  File "/home/klipper/moonraker/moonraker/components/machine.py", line 627, in _parse_network_interfaces
    resp = await self.addr_cmd.run_with_response(log_complete=False)
  File "/home/klipper/moonraker/moonraker/components/shell_command.py", line 276, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'ip -json -det address'
2023-12-08 10:42:31,893 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.8.8
2023-12-08 19:00:12,723 [proc_stats.py:_watchdog_callback()] - EVENT LOOP BLOCKED: 4.05 seconds, total blocked count: 1
2023-12-08 19:00:14,046 [proc_stats.py:log_last_stats()] - 
System Time: 1702051204.761142, Usage: 1.25%, Memory: 13268 kB
System Time: 1702051205.761082, Usage: 1.59%, Memory: 13264 kB
System Time: 1702051206.765481, Usage: 1.3%, Memory: 13200 kB
System Time: 1702051211.028240, Usage: 1.56%, Memory: 13200 kB
System Time: 1702051213.858263, Usage: 0.28%, Memory: 13068 kB
2023-12-08 22:23:37,054 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2023-12-08 22:23:48,206 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2023-12-08 22:23:51,914 [server.py:add_log_rollover_item()] - Klipper Version: v0.11.0-277-g21b78429-dirty
2023-12-08 22:24:38,074 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.8.10
2023-12-08 22:24:38,092 [app.py:log_request()] - 101 GET /websocket (192.168.8.10) [_TRUSTED_USER_] 57.54ms
2023-12-08 22:24:38,094 [websockets.py:open()] - Websocket Opened: ID: 2803293800, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0, Host Name: 192.168.8.8
2023-12-08 22:24:38,105 [websockets.py:_handle_identify()] - Websocket 2803293800 Client Identified - Name: mainsail, Version: 2.7.1, Type: web
2023-12-08 22:25:22,091 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2023-12-08 22:25:22,095 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2023-12-08 22:25:22,100 [klippy_connection.py:_check_ready()] - 
mcu 'mcu': Unable to connect
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer

2023-12-08 22:26:56,213 [app.py:prepare()] - Upload Request Received from 192.168.8.10
2023-12-08 22:26:56,241 [app.py:post()] - Processing Uploaded File: macros.cfg
2023-12-08 22:26:56,262 [app.py:log_request()] - 201 POST /server/files/upload (192.168.8.10) [_TRUSTED_USER_] 59.25ms
2023-12-08 22:26:57,368 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2023-12-08 22:26:57,624 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2023-12-08 22:28:30,544 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2023-12-08 22:28:30,547 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2023-12-08 22:28:30,553 [klippy_connection.py:_check_ready()] - 
mcu 'mcu': Unable to connect
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer

2023-12-08 22:35:58,476 [websockets.py:write_to_socket()] - Websocket closed while writing: 2803293800
2023-12-08 22:36:03,101 [websockets.py:on_close()] - Websocket Closed: ID: 2803293800 Close Code: None, Close Reason: None, Pong Time Elapsed: 45.00
2023-12-08 22:40:48,062 [app.py:log_request()] - 101 GET /websocket (192.168.8.10) [_TRUSTED_USER_] 29.92ms
2023-12-08 22:40:48,064 [websockets.py:open()] - Websocket Opened: ID: 2803293320, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0, Host Name: 192.168.8.8
2023-12-08 22:40:48,079 [websockets.py:_handle_identify()] - Websocket 2803293320 Client Identified - Name: mainsail, Version: 2.7.1, Type: web
2023-12-08 22:41:19,720 [app.py:prepare()] - Upload Request Received from 192.168.8.10
2023-12-08 22:41:19,731 [app.py:post()] - Processing Uploaded File: macros.cfg
2023-12-08 22:41:19,751 [app.py:log_request()] - 201 POST /server/files/upload (192.168.8.10) [_TRUSTED_USER_] 40.61ms
2023-12-08 22:41:21,120 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2023-12-08 22:41:21,376 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2023-12-08 22:42:54,233 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2023-12-08 22:42:54,237 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2023-12-08 22:42:54,242 [klippy_connection.py:_check_ready()] - 
mcu 'mcu': Unable to connect
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer

